version: '2'
services:
 alfresco:
  build: ./alfresco
  links:
   - solr4
   - libreoffice
  extra_hosts:
   - "montrahost:$DOCKERHOST"
  ports:
    - 8081:8080

 db:
  build: ./postgres
  network_mode: service:alfresco
  environment:
   - POSTGRES_DB=alfresco
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=alfresco

 solr4:
  build: ./solr4
  ports:
    - 8082:8080

 libreoffice:
  image: xcgd/libreoffice
 
